"""Constants for the BIS Scraper package."""

from typing import Dict, List

# Institution list with their common variations
INSTITUTIONS: List[str] = [
    "People's Bank of China",
    "Bank Indonesia",
    "Bank of Albania",
    "Bank of Algeria",
    "Bank of Botswana",
    "Bank of Canada",
    "Bank of England",
    "Bank of Estonia",
    "Bank of Finland",
    "Bank of France",
    "Bank of Ghana",
    "Bank of Greece",
    "Bank of Guatemala",
    "Bank of Guyana",
    "Bank of Israel",
    "Bank of Italy",
    "Bank of Jamaica",
    "Bank of Japan",
    "Bank of Korea",
    "Bank of Latvia",
    "Bank of Lithuania",
    "Bank of Mauritius",
    "Bank of Mexico",
    "Bank of Morocco",
    "Bank of Mozambique",
    "Bank of Namibia",
    "Bank of Papua New Guinea",
    "Bank of Portugal",
    "Bank of Sierra Leone",
    "Bank of Slovenia",
    "Bank of Spain",
    "Bank of Tanzania",
    "Bank of Thailand",
    "Bank of Uganda",
    "Bank of Zambia",
    "Board of Governors of the Federal Reserve System",
    "Bulgarian National Bank",
    "Central Bank of Argentina",
    "Central Bank of Armenia",
    "Central Bank of Aruba",
    "Central Bank of Bahrain",
    "Central Bank of Barbados",
    "Central Bank of Belize",
    "Central Bank of Bolivia",
    "Central Bank of Bosnia and Herzegovina",
    "Central Bank of Brazil",
    "Central Bank of Chile",
    "Central Bank of Colombia",
    "Central Bank of Curaçao and Sint Maarten",
    "Central Bank of Cyprus",
    "Central Bank of Eswatini",
    "Central Bank of Iceland",
    "Central Bank of Ireland",
    "Central Bank of Jordan",
    "Central Bank of Kenya",
    "Central Bank of Kuwait",
    "Central Bank of Luxembourg",
    "Central Bank of Malaysia",
    "Central Bank of Malta",
    "Central Bank of Nepal",
    "Central Bank of Nigeria",
    "Central Bank of Norway",
    "Central Bank of Samoa",
    "Central Bank of Seychelles",
    "Central Bank of Solomon Islands",
    "Central Bank of Sri Lanka",
    "Central Bank of The Bahamas",
    "Central Bank of Trinidad and Tobago",
    "Central Bank of Uruguay",
    "central bank of the Philippines",
    "Central Bank of the Republic of Kosovo",
    "Central Bank of the Republic of Turkey",
    "Bank of Russia",
    "Central Bank of the United Arab Emirates",
    "Croatian National Bank",
    "Czech National Bank",
    "National Bank of Denmark",
    "Deutsche Bundesbank",
    "Eastern Caribbean Central Bank",
    "European Central Bank",
    "Federal Reserve Bank of Atlanta",
    "Federal Reserve Bank of Boston",
    "Federal Reserve Bank of Chicago",
    "Federal Reserve Bank of Dallas",
    "Federal Reserve Bank of Kansas City",
    "Federal Reserve Bank of Minneapolis",
    "Federal Reserve Bank of New York",
    "Federal Reserve Bank of Philadelphia",
    "Federal Reserve Bank of Richmond",
    "Federal Reserve Bank of San Francisco",
    "Hong Kong Monetary Authority",
    "Cayman Islands Monetary Authority",
    "central bank of Hungary",
    "Maldives Monetary Authority",
    "Monetary Authority of Macao",
    "Monetary Authority of Singapore",
    "National Bank of Belgium",
    "National Bank of Cambodia",
    "National Bank of Romania",
    "National Bank of Serbia",
    "National Bank of Slovakia",
    "National Bank of Ukraine",
    "Central Bank of the Republic of Austria",
    "National Bank of North Macedonia",
    "Netherlands Bank",
    "Reserve Bank of Australia",
    "Reserve Bank of Fiji",
    "Central Bank of The Gambia",
    "Reserve Bank of India",
    "Reserve Bank of Malawi",
    "Reserve Bank of New Zealand",
    "Reserve Bank of Vanuatu",
    "Saudi Arabian Monetary Agency",
    "South African Reserve Bank",
    "State Bank of Pakistan",
    "Sveriges Riksbank",
    "Swiss National Bank",
    "Board of Governors of the US Federal Reserve System",
    "Bank of Sweden",
    "Board of the US Federal Reserve System",
    "US Federal Reserve System",
    "European Monetary Institute",
    "Bank for International Settlements",
    "Norges Bank",
    "Board of Governors of the US Federal Reserve",
    "Nederlandsche Bank",
    "Banque de France",
    "International Monetary Fund",
    "Austrian National Bank",
    "Governors of the U.S. Federal Reserve System",
    "Swedish Central Bank",
    "Board of the U S Federal Reserve System",
    "Bank of South Africa",
    "Banque nationale suisse",
    "Hong Kong Monetary",
    "Oesterreichische Nationalbank",
    "Sveriges Riskbank",
    "Bank of India",
    "National Bank of the Republic of Macedonia",
    "National Bank of the Republic of North Macedonia",
    "ECB",
    "Authority of Ireland",
    "Bank of Turkey",
    "Bank of Poland",
    "Bank of China",
    "Board of Governors of the federal reserve",
    "Board of governors of the us fed",
    "Australian Reserve Bank",
    "Sveriges Risksbank",
    "Federal Reserve Board",
    "Austrian Nationalbank",
    "Bank of Australia",
    "Board of Governors of the US Fed",
    "Federal Reserve System",
]

# BIS website URL patterns
BASE_URL = "https://www.bis.org/review"
PDF_EXTENSION = ".pdf"
HTML_EXTENSION = ".htm"

# Directory structure
RAW_DATA_DIR = "pdfs"
TXT_DATA_DIR = "texts"

# URLs for speech listing page
SPEECHES_URL = "https://www.bis.org/review"

# Institution name mappings for standardization
INSTITUTION_ALIASES: Dict[str, List[str]] = {
    "board of governors of the federal reserve system": [
        "board of governors of the us federal reserve system",
        "board of the us federal reserve system",
        "us federal reserve system",
        "board of governors of the us federal reserve",
        "governors of the u.s. federal reserve system",
        "board of the u s federal reserve system",
        "board of governors of the federal reserve",
        "board of governors of the us fed",
        "federal reserve board",
        "board of governors of the us fed",
        "federal reserve system",
        "bd. of govnrs. of the us fed. res. system",
        "chairman of the bd. of govnrs. of the us fed. res. system",
    ],
    "sveriges riksbank": [
        "bank of sweden",
        "sveriges riskbank",
        "swedish central bank",
        "sveriges risksbank",
        "heikensten",  # Former governor
    ],
    "central bank of the republic of austria": [
        "austrian national bank",
        "oesterreichische nationalbank",
        "austrian nationalbank",
    ],
    "central bank of norway": ["norges bank"],
    "bank of france": ["banque de france", "banque of france"],  # Typo variant
    "federal reserve bank of new york": [
        "president and chief executive officer of the federal reserve bank of new york",
        "federal\nreserve bank of new york",  # Handle line breaks in metadata
        "fed. res. bank of new york",
        "fed res bank of new york",
        "federal reserve bank of ny",
    ],
    "national bank of belgium": ["pierre wunsch"],  # Governor name
    "european central bank": [
        "ecb",
        "european central",
        "member of the executive board of the european central",
        "willem f duisenberg",  # Former president
        "mario draghi",  # Former president
    ],
    "bank of portugal": ["banco de portugal"],
    "bank of spain": ["banco de españa", "the banco de españa"],
    "central bank of colombia": [
        "banco de la república",
        "banco de la república (bank of the republic)",
        "bank of the republic",
        "co-director of the bank of the republic",
    ],
    "central bank of malaysia": [
        "bank negara malaysia",
        "the bank negara malaysia",
        "the bank of malaysia",
        "negara malaysia",
        "cb of malaysia",
    ],
    "central bank of the philippines": [
        "bangko sentral ng pilipinas",
        "the bangko sentral ng pilipinas",
    ],
    "central bank of trinidad and tobago": [
        "trinidad & tobago",
        "the central bank of trinidad & tobago",
        "of trinidad & tobago",
    ],
    "central bank of the republic of turkey": [
        "bank of turkey",
        "the republic of türkiye",
        "the central bank of the republic of türkiye",
        "for the republic of turkey",
        "central bank for the republic of turkey",
    ],
    "central bank of curaçao and sint maarten": [
        "netherlands antilles",
        "the netherlands antilles",
        "bank of the netherlands antilles",
        "the bank of the netherlands antilles",
        "bank van de nederlandse antillen",
        "the bank van de nederlandse antillen",
        "the netherlands antilles (bank van de nederlandse antillen)",
        "the bank of the netherlands antilles (bank van de nederlandse antillen)",
        "central bank of curacao and sint maarten",
        "centrale bank van curaçao en sint maarten",
        "van curaçao en sint maarten",
        "of curacao and sint maarten",
    ],
    "central bank of armenia": ["armenia", "of armenia"],
    "central bank of the gambia": ["the gambia", "of the gambia"],
    "central bank of hungary": [
        "magyar nemzeti bank",
        "magyar nemzeti bank (hungary's central bank)",
        "deputy governor of magyar nemzeti bank (hungary's",
    ],
    "national bank of denmark": [
        "danmarks nationalbank",
        "danmarks national bank",
        "governor of danmarks",
    ],
    "reserve bank of new zealand": [
        "reserve of the bank of new zealand",
        "of new zealand",
    ],
    "croatian national bank": ["croation national bank", "the croation national bank"],
    "netherlands bank": ["nederlandsche bank"],
    "south african reserve bank": ["bank of south africa"],
    "hong kong monetary authority": ["hong kong monetary"],
    "reserve bank of india": ["bank of india"],
    "national bank of north macedonia": [
        "national bank of the republic of macedonia",
        "national bank of the republic of north macedonia",
    ],
    "central bank of ireland": ["authority of ireland"],
    "bank indonesia": ["bank of indonesia", "the bank of indonesia"],
    "bank of uganda": ["bank of the uganda"],
    "central bank of bahrain": [
        "bahrain monetary agency",
        "the bahrain monetary agency",
    ],
    "monetary authority of macao": [
        "mon. authority of macao",
        "chairman of the mon. authority of macao",
    ],
    "bank of italy": ["baml of italy", "the baml of italy"],
    "bank of israel": ["stanley fischer"],  # Former governor
    "state bank of pakistan": ["ishrat husain"],  # Former governor
    "people's bank of china": ["bank of china"],
    "reserve bank of australia": ["australian reserve bank", "bank of australia"],
    "saudi arabian monetary agency": ["saudi central bank"],
}
